---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    app.quarkus.io/quarkus-version: 3.24.4
    app.quarkus.io/build-timestamp: 2025-07-28 - 19:00:21 +0000
  labels:
    app.kubernetes.io/name: storage-service
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
    app.kubernetes.io/managed-by: quarkus
  name: storage-service
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app.kubernetes.io/name: storage-service
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
  name: view-jobs
rules:
  - apiGroups:
      - batch
    resources:
      - jobs
    verbs:
      - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/name: storage-service
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
  name: storage-service-view-jobs
roleRef:
  kind: Role
  apiGroup: rbac.authorization.k8s.io
  name: view-jobs
subjects:
  - kind: ServiceAccount
    apiGroup: ""
    name: storage-service
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    app.quarkus.io/quarkus-version: 3.24.4
    app.quarkus.io/build-timestamp: 2025-07-28 - 19:00:21 +0000
  labels:
    app.kubernetes.io/name: storage-service
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
    app.kubernetes.io/managed-by: quarkus
  name: storage-service
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 9091
  selector:
    app.kubernetes.io/name: storage-service
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app.quarkus.io/quarkus-version: 3.24.4
    app.quarkus.io/build-timestamp: 2025-07-28 - 19:00:21 +0000
  labels:
    app.kubernetes.io/name: storage-service
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
    app.kubernetes.io/managed-by: quarkus
  name: storage-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/version: 1.0.0-SNAPSHOT
      app.kubernetes.io/name: storage-service
  template:
    metadata:
      annotations:
        app.quarkus.io/quarkus-version: 3.24.4
        app.quarkus.io/build-timestamp: 2025-07-28 - 19:00:21 +0000
      labels:
        app.kubernetes.io/managed-by: quarkus
        app.kubernetes.io/version: 1.0.0-SNAPSHOT
        app.kubernetes.io/name: storage-service
    spec:
      containers:
        - env:
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: QUARKUS_LIQUIBASE_ENABLED
              value: "false"
          image: docker.io/stepa/storage-service:1.0.0-SNAPSHOT
          imagePullPolicy: Always
          name: storage-service
          ports:
            - containerPort: 9091
              name: http
              protocol: TCP
      initContainers:
        - args:
            - job
            - storage-service-liquibase-init
          image: groundnuty/k8s-wait-for:no-root-v1.7
          imagePullPolicy: Always
          name: wait-for-liquibase
      serviceAccountName: storage-service
---
apiVersion: batch/v1
kind: Job
metadata:
  name: storage-service-liquibase-init
spec:
  completionMode: NonIndexed
  template:
    metadata: {}
    spec:
      containers:
        - env:
            - name: QUARKUS_LIQUIBASE_ENABLED
              value: "true"
            - name: QUARKUS_INIT_AND_EXIT
              value: "true"
          image: docker.io/stepa/storage-service:1.0.0-SNAPSHOT
          name: storage-service-liquibase-init
      restartPolicy: OnFailure
      serviceAccountName: storage-service
